/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RequestsRouteImport } from "./routes/requests";
import { Route as NodesRouteImport } from "./routes/nodes";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DemoTanstackQueryRouteImport } from "./routes/demo/tanstack-query";
import { Route as DemoTableRouteImport } from "./routes/demo/table";

const RequestsRoute = RequestsRouteImport.update({
	id: "/requests",
	path: "/requests",
	getParentRoute: () => rootRouteImport,
} as any);
const NodesRoute = NodesRouteImport.update({
	id: "/nodes",
	path: "/nodes",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
	id: "/demo/tanstack-query",
	path: "/demo/tanstack-query",
	getParentRoute: () => rootRouteImport,
} as any);
const DemoTableRoute = DemoTableRouteImport.update({
	id: "/demo/table",
	path: "/demo/table",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/nodes": typeof NodesRoute;
	"/requests": typeof RequestsRoute;
	"/demo/table": typeof DemoTableRoute;
	"/demo/tanstack-query": typeof DemoTanstackQueryRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/nodes": typeof NodesRoute;
	"/requests": typeof RequestsRoute;
	"/demo/table": typeof DemoTableRoute;
	"/demo/tanstack-query": typeof DemoTanstackQueryRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/nodes": typeof NodesRoute;
	"/requests": typeof RequestsRoute;
	"/demo/table": typeof DemoTableRoute;
	"/demo/tanstack-query": typeof DemoTanstackQueryRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| "/nodes"
		| "/requests"
		| "/demo/table"
		| "/demo/tanstack-query";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/nodes" | "/requests" | "/demo/table" | "/demo/tanstack-query";
	id:
		| "__root__"
		| "/"
		| "/nodes"
		| "/requests"
		| "/demo/table"
		| "/demo/tanstack-query";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	NodesRoute: typeof NodesRoute;
	RequestsRoute: typeof RequestsRoute;
	DemoTableRoute: typeof DemoTableRoute;
	DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/requests": {
			id: "/requests";
			path: "/requests";
			fullPath: "/requests";
			preLoaderRoute: typeof RequestsRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/nodes": {
			id: "/nodes";
			path: "/nodes";
			fullPath: "/nodes";
			preLoaderRoute: typeof NodesRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/demo/tanstack-query": {
			id: "/demo/tanstack-query";
			path: "/demo/tanstack-query";
			fullPath: "/demo/tanstack-query";
			preLoaderRoute: typeof DemoTanstackQueryRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/demo/table": {
			id: "/demo/table";
			path: "/demo/table";
			fullPath: "/demo/table";
			preLoaderRoute: typeof DemoTableRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	NodesRoute: NodesRoute,
	RequestsRoute: RequestsRoute,
	DemoTableRoute: DemoTableRoute,
	DemoTanstackQueryRoute: DemoTanstackQueryRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
