// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Node struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	LocationX         float64          `json:"location_x"`
	LocationY         float64          `json:"location_y"`
	Endpoint          string           `json:"endpoint"`
	Capacity          pgtype.Int4      `json:"capacity"`
	Status            pgtype.Text      `json:"status"`
	CpuUsage          pgtype.Float8    `json:"cpu_usage"`
	MemoryUsage       pgtype.Float8    `json:"memory_usage"`
	ActiveConnections pgtype.Int4      `json:"active_connections"`
	LastHealthCheck   pgtype.Timestamp `json:"last_health_check"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type RoutingRequest struct {
	ID                pgtype.UUID      `json:"id"`
	RequestID         string           `json:"request_id"`
	CoordinatesX      float64          `json:"coordinates_x"`
	CoordinatesY      float64          `json:"coordinates_y"`
	SelectedNodeID    pgtype.UUID      `json:"selected_node_id"`
	Distance          pgtype.Float8    `json:"distance"`
	LoadScore         pgtype.Float8    `json:"load_score"`
	Status            pgtype.Text      `json:"status"`
	ResponseTimeMs    pgtype.Int4      `json:"response_time_ms"`
	RequestData       []byte           `json:"request_data"`
	ResponseData      []byte           `json:"response_data"`
	Metadata          []byte           `json:"metadata"`
	ClientInfo        []byte           `json:"client_info"`
	ProcessingMetrics []byte           `json:"processing_metrics"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type SystemMetric struct {
	ID         pgtype.UUID      `json:"id"`
	MetricType string           `json:"metric_type"`
	NodeID     pgtype.UUID      `json:"node_id"`
	Value      float64          `json:"value"`
	Timestamp  pgtype.Timestamp `json:"timestamp"`
}
