// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, location_x, location_y, endpoint, capacity, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, location_x, location_y, endpoint, capacity, status, cpu_usage, memory_usage, active_connections, last_health_check, created_at, updated_at
`

type CreateNodeParams struct {
	Name      string      `json:"name"`
	LocationX float64     `json:"location_x"`
	LocationY float64     `json:"location_y"`
	Endpoint  string      `json:"endpoint"`
	Capacity  pgtype.Int4 `json:"capacity"`
	Status    pgtype.Text `json:"status"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.Name,
		arg.LocationX,
		arg.LocationY,
		arg.Endpoint,
		arg.Capacity,
		arg.Status,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationX,
		&i.LocationY,
		&i.Endpoint,
		&i.Capacity,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.ActiveConnections,
		&i.LastHealthCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getAllNodes = `-- name: GetAllNodes :many
SELECT id, name, location_x, location_y, endpoint, capacity, status, cpu_usage, memory_usage, active_connections, last_health_check, created_at, updated_at FROM nodes ORDER BY created_at DESC
`

func (q *Queries) GetAllNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, getAllNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocationX,
			&i.LocationY,
			&i.Endpoint,
			&i.Capacity,
			&i.Status,
			&i.CpuUsage,
			&i.MemoryUsage,
			&i.ActiveConnections,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHealthyNodes = `-- name: GetHealthyNodes :many
SELECT id, name, location_x, location_y, endpoint, capacity, status, cpu_usage, memory_usage, active_connections, last_health_check, created_at, updated_at FROM nodes WHERE status = 'healthy' ORDER BY created_at DESC
`

func (q *Queries) GetHealthyNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, getHealthyNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LocationX,
			&i.LocationY,
			&i.Endpoint,
			&i.Capacity,
			&i.Status,
			&i.CpuUsage,
			&i.MemoryUsage,
			&i.ActiveConnections,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, location_x, location_y, endpoint, capacity, status, cpu_usage, memory_usage, active_connections, last_health_check, created_at, updated_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id pgtype.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationX,
		&i.LocationY,
		&i.Endpoint,
		&i.Capacity,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.ActiveConnections,
		&i.LastHealthCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes 
SET name = $2, location_x = $3, location_y = $4, endpoint = $5, capacity = $6, status = $7,
    cpu_usage = $8, memory_usage = $9, active_connections = $10,
    last_health_check = $11, updated_at = NOW()
WHERE id = $1
RETURNING id, name, location_x, location_y, endpoint, capacity, status, cpu_usage, memory_usage, active_connections, last_health_check, created_at, updated_at
`

type UpdateNodeParams struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	LocationX         float64          `json:"location_x"`
	LocationY         float64          `json:"location_y"`
	Endpoint          string           `json:"endpoint"`
	Capacity          pgtype.Int4      `json:"capacity"`
	Status            pgtype.Text      `json:"status"`
	CpuUsage          pgtype.Float8    `json:"cpu_usage"`
	MemoryUsage       pgtype.Float8    `json:"memory_usage"`
	ActiveConnections pgtype.Int4      `json:"active_connections"`
	LastHealthCheck   pgtype.Timestamp `json:"last_health_check"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.Name,
		arg.LocationX,
		arg.LocationY,
		arg.Endpoint,
		arg.Capacity,
		arg.Status,
		arg.CpuUsage,
		arg.MemoryUsage,
		arg.ActiveConnections,
		arg.LastHealthCheck,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationX,
		&i.LocationY,
		&i.Endpoint,
		&i.Capacity,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.ActiveConnections,
		&i.LastHealthCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeHealth = `-- name: UpdateNodeHealth :one
UPDATE nodes 
SET status = $2, cpu_usage = $3, memory_usage = $4, active_connections = $5,
    last_health_check = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, location_x, location_y, endpoint, capacity, status, cpu_usage, memory_usage, active_connections, last_health_check, created_at, updated_at
`

type UpdateNodeHealthParams struct {
	ID                pgtype.UUID      `json:"id"`
	Status            pgtype.Text      `json:"status"`
	CpuUsage          pgtype.Float8    `json:"cpu_usage"`
	MemoryUsage       pgtype.Float8    `json:"memory_usage"`
	ActiveConnections pgtype.Int4      `json:"active_connections"`
	LastHealthCheck   pgtype.Timestamp `json:"last_health_check"`
}

func (q *Queries) UpdateNodeHealth(ctx context.Context, arg UpdateNodeHealthParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeHealth,
		arg.ID,
		arg.Status,
		arg.CpuUsage,
		arg.MemoryUsage,
		arg.ActiveConnections,
		arg.LastHealthCheck,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LocationX,
		&i.LocationY,
		&i.Endpoint,
		&i.Capacity,
		&i.Status,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.ActiveConnections,
		&i.LastHealthCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
