// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateRoutingRequest(ctx context.Context, arg CreateRoutingRequestParams) (RoutingRequest, error)
	CreateSystemMetric(ctx context.Context, arg CreateSystemMetricParams) (SystemMetric, error)
	DeleteNode(ctx context.Context, id pgtype.UUID) error
	GetAllNodes(ctx context.Context) ([]Node, error)
	GetHealthyNodes(ctx context.Context) ([]Node, error)
	GetNodeByID(ctx context.Context, id pgtype.UUID) (Node, error)
	GetRecentRoutingRequests(ctx context.Context, limit int32) ([]RoutingRequest, error)
	GetRecentSystemMetrics(ctx context.Context, limit int32) ([]SystemMetric, error)
	GetRoutingRequestByID(ctx context.Context, id pgtype.UUID) (RoutingRequest, error)
	GetRoutingRequestsByNode(ctx context.Context, arg GetRoutingRequestsByNodeParams) ([]RoutingRequest, error)
	GetRoutingRequestsByStatus(ctx context.Context, arg GetRoutingRequestsByStatusParams) ([]RoutingRequest, error)
	SearchRoutingRequests(ctx context.Context, arg SearchRoutingRequestsParams) ([]RoutingRequest, error)
	UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error)
	UpdateNodeHealth(ctx context.Context, arg UpdateNodeHealthParams) (Node, error)
	UpdateRoutingResponse(ctx context.Context, arg UpdateRoutingResponseParams) (RoutingRequest, error)
}

var _ Querier = (*Queries)(nil)
