// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemMetric = `-- name: CreateSystemMetric :one
INSERT INTO system_metrics (metric_type, node_id, value)
VALUES ($1, $2, $3)
RETURNING id, metric_type, node_id, value, timestamp
`

type CreateSystemMetricParams struct {
	MetricType string      `json:"metric_type"`
	NodeID     pgtype.UUID `json:"node_id"`
	Value      float64     `json:"value"`
}

func (q *Queries) CreateSystemMetric(ctx context.Context, arg CreateSystemMetricParams) (SystemMetric, error) {
	row := q.db.QueryRow(ctx, createSystemMetric, arg.MetricType, arg.NodeID, arg.Value)
	var i SystemMetric
	err := row.Scan(
		&i.ID,
		&i.MetricType,
		&i.NodeID,
		&i.Value,
		&i.Timestamp,
	)
	return i, err
}

const getRecentSystemMetrics = `-- name: GetRecentSystemMetrics :many
SELECT id, metric_type, node_id, value, timestamp FROM system_metrics 
ORDER BY timestamp DESC 
LIMIT $1
`

func (q *Queries) GetRecentSystemMetrics(ctx context.Context, limit int32) ([]SystemMetric, error) {
	rows, err := q.db.Query(ctx, getRecentSystemMetrics, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemMetric
	for rows.Next() {
		var i SystemMetric
		if err := rows.Scan(
			&i.ID,
			&i.MetricType,
			&i.NodeID,
			&i.Value,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
